spring.application.name=wheat-store
spring.datasource.url=jdbc:mysql://localhost:3306/wheatstore
spring.datasource.username=root
spring.datasource.password=Aditya@1

spring.jpa.hibernate.ddl-auto=update 

spring.jpa.show-sql=true

# Store UUID as CHAR(36) instead of BINARY(16/36) in MySQL
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

